name: GitHub Action Test
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        # https://github.com/actions/hello-world-javascript-action
        with:
          who-to-greet: Evano
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"