name: Simple Workflow
on: [push]

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
            - name: Multiline Command
              run: |
                node -v
                npm -v
        