name: Working Dirs, Shells, & Downloading Repo
on: [push]
defaults:
  run:
    shell: bash
    # working-directory: /de/ed
jobs:
  display-wd-info-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change Working Dir
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python Shell
        shell: python
        run: |
          import platform 
          print(platform.processor())
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -a
  use-actions-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: List Files After
        run: ls -a